import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    paddingHorizontal: 18,
  },
  keyboardAvoidContainer: {
    flex: 1,
  },
  loader: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5fbf8',
  },
  header: {
    paddingTop: 8,
    paddingBottom: 12,
  },
  appTitle: {
    fontSize: 28,
    color: '#0f4c5c',
    fontFamily: 'Sora_700Bold',
  },
  appSubtitle: {
    marginTop: 6,
    fontSize: 14,
    color: '#2b5b67',
    fontFamily: 'Sora_400Regular',
  },
  progressWrap: {
    marginBottom: 10,
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#d7ece8',
    overflow: 'hidden',
  },
  progressFill: {
    height: 8,
    backgroundColor: '#0e766e',
    borderRadius: 999,
  },
  progressText: {
    marginTop: 7,
    color: '#3b6369',
    fontFamily: 'Sora_600SemiBold',
    fontSize: 12,
  },
  contentContainer: {
    paddingBottom: 22,
  },
  stepCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    borderRadius: 24,
    padding: 16,
    borderWidth: 1,
    borderColor: '#dbefea',
    shadowColor: '#235a57',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
  },
  stepTitle: {
    fontSize: 18,
    color: '#18353e',
    fontFamily: 'Sora_700Bold',
  },
  stepHint: {
    marginTop: 6,
    marginBottom: 12,
    fontSize: 13,
    color: '#44656d',
    lineHeight: 19,
    fontFamily: 'Sora_400Regular',
  },
  noticeText: {
    marginBottom: 10,
    color: '#7a5d13',
    fontFamily: 'Sora_600SemiBold',
    fontSize: 12,
  },
  noticeOverlay: {
    flex: 1,
    backgroundColor: 'rgba(10, 30, 35, 0.28)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  noticeCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: '#d7ece8',
  },
  noticeTitle: {
    fontFamily: 'Sora_700Bold',
    fontSize: 18,
    marginBottom: 8,
  },
  noticeTitleInfo: {
    color: '#134c58',
  },
  noticeTitleSuccess: {
    color: '#0f766e',
  },
  noticeTitleError: {
    color: '#b42318',
  },
  noticeMessage: {
    fontFamily: 'Sora_400Regular',
    color: '#355962',
    lineHeight: 21,
    fontSize: 14,
  },
  noticeButton: {
    marginTop: 16,
    backgroundColor: '#0e766e',
    borderRadius: 10,
    alignSelf: 'flex-end',
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  noticeButtonText: {
    color: '#ffffff',
    fontFamily: 'Sora_600SemiBold',
    fontSize: 13,
  },
  map: {
    height: 270,
    borderRadius: 16,
    overflow: Platform.OS === 'android' ? 'hidden' : 'visible',
  },
  mapWebContainer: {
    height: 270,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#d1e6e2',
  },
  mapWebView: {
    flex: 1,
    backgroundColor: '#f4f7f6',
  },
  addressText: {
    marginTop: 10,
    fontSize: 12,
    color: '#355b58',
    fontFamily: 'Sora_600SemiBold',
  },
  progressPanel: {
    marginTop: 14,
    borderWidth: 1,
    borderColor: '#d6ebe6',
    borderRadius: 12,
    padding: 12,
    backgroundColor: '#f8fdfa',
  },
  progressPanelTitle: {
    fontFamily: 'Sora_700Bold',
    fontSize: 14,
    color: '#1b4e57',
    marginBottom: 8,
  },
  progressBarTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#dbeee9',
    overflow: 'hidden',
    marginBottom: 8,
  },
  progressBarFill: {
    height: 8,
    backgroundColor: '#0e766e',
    borderRadius: 999,
  },
  progressLine: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  progressIcon: {
    width: 18,
    height: 18,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  progressIconDone: {
    backgroundColor: '#1f8a5b',
  },
  progressIconActive: {
    borderWidth: 2,
    borderColor: '#0e766e',
    backgroundColor: '#e9f7f4',
  },
  progressIconPending: {
    borderWidth: 1,
    borderColor: '#c9e0dc',
    backgroundColor: '#ffffff',
  },
  progressIconText: {
    fontSize: 11,
    fontFamily: 'Sora_700Bold',
    lineHeight: 13,
  },
  progressIconTextDone: {
    color: '#ffffff',
  },
  progressIconTextActive: {
    color: '#0e766e',
  },
  progressIconTextPending: {
    color: '#8aa9a4',
  },
  progressLabel: {
    flex: 1,
    fontSize: 12,
    fontFamily: 'Sora_400Regular',
  },
  progressLabelDone: {
    color: '#1f8a5b',
  },
  progressLabelActive: {
    color: '#0e766e',
    fontFamily: 'Sora_600SemiBold',
  },
  progressLabelPending: {
    color: '#7f9d9a',
  },
  progressDuration: {
    marginLeft: 8,
    fontSize: 11,
    color: '#6f8e8a',
    fontFamily: 'Sora_600SemiBold',
  },
  chipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#e8f3ef',
  },
  chipActive: {
    backgroundColor: '#0e766e',
  },
  chipText: {
    color: '#365b57',
    fontFamily: 'Sora_600SemiBold',
    fontSize: 12,
  },
  chipTextActive: {
    color: '#ffffff',
  },
  textArea: {
    minHeight: 170,
    textAlignVertical: 'top',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#c8e0db',
    backgroundColor: '#f8fdfb',
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#1d4048',
    fontFamily: 'Sora_400Regular',
    fontSize: 14,
    lineHeight: 20,
  },
  counterText: {
    marginTop: 8,
    color: '#66838b',
    fontFamily: 'Sora_400Regular',
    fontSize: 12,
  },
  groupLabel: {
    marginBottom: 8,
    marginTop: 2,
    color: '#335862',
    fontFamily: 'Sora_600SemiBold',
    fontSize: 13,
  },
  photoButton: {
    backgroundColor: '#f19832',
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: 'center',
    marginBottom: 12,
  },
  photoButtonText: {
    color: '#ffffff',
    fontFamily: 'Sora_700Bold',
    fontSize: 13,
  },
  photoList: {
    minHeight: 96,
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  emptyPhotoText: {
    color: '#6b8b8f',
    fontFamily: 'Sora_400Regular',
    fontSize: 12,
  },
  photoItem: {
    width: 94,
    height: 94,
    borderRadius: 10,
  },
  input: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#c8e0db',
    backgroundColor: '#f8fdfb',
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#1d4048',
    fontFamily: 'Sora_400Regular',
    marginTop: 9,
  },
  rewriteButton: {
    backgroundColor: '#157f71',
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: 'center',
    marginBottom: 12,
  },
  rewriteButtonText: {
    color: '#ffffff',
    fontFamily: 'Sora_700Bold',
    fontSize: 13,
  },
  formalTextArea: {
    minHeight: 290,
    textAlignVertical: 'top',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#c8e0db',
    backgroundColor: '#f8fdfb',
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#1d4048',
    fontFamily: 'Sora_400Regular',
    fontSize: 14,
    lineHeight: 20,
  },
  successTitle: {
    marginTop: 18,
    fontSize: 16,
    color: '#1f4f57',
    fontFamily: 'Sora_600SemiBold',
  },
  successCode: {
    marginTop: 10,
    marginBottom: 14,
    fontSize: 23,
    color: '#0e766e',
    letterSpacing: 0.4,
    fontFamily: 'Sora_700Bold',
  },
  trackingCodeText: {
    marginTop: -2,
    marginBottom: 8,
    color: '#2f5f68',
    fontSize: 12,
    fontFamily: 'Sora_600SemiBold',
  },
  statusPanel: {
    marginTop: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d2e7e2',
    backgroundColor: '#f6fcfa',
    padding: 12,
  },
  statusPanelTitle: {
    color: '#1d4f58',
    fontSize: 14,
    marginBottom: 8,
    fontFamily: 'Sora_700Bold',
  },
  statusValueText: {
    color: '#214c54',
    fontSize: 13,
    fontFamily: 'Sora_600SemiBold',
  },
  statusMetaText: {
    marginTop: 6,
    color: '#42656d',
    fontSize: 12,
    fontFamily: 'Sora_400Regular',
  },
  statusErrorText: {
    marginTop: 8,
    color: '#b42318',
    fontSize: 12,
    fontFamily: 'Sora_600SemiBold',
  },
  statusRefreshButton: {
    marginTop: 10,
    borderRadius: 10,
    backgroundColor: '#0f4c5c',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  statusRefreshButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontFamily: 'Sora_700Bold',
  },
  timelineWrap: {
    marginTop: 12,
    gap: 8,
  },
  timelineItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  timelineDot: {
    width: 9,
    height: 9,
    marginTop: 4,
    borderRadius: 99,
    backgroundColor: '#0e766e',
    marginRight: 8,
  },
  timelineContent: {
    flex: 1,
  },
  timelineTitle: {
    color: '#1f4e57',
    fontSize: 12,
    fontFamily: 'Sora_600SemiBold',
  },
  timelineDetail: {
    marginTop: 2,
    color: '#4e6e76',
    fontSize: 11,
    fontFamily: 'Sora_400Regular',
    lineHeight: 16,
  },
  timelineDate: {
    marginTop: 2,
    color: '#6f8e96',
    fontSize: 11,
    fontFamily: 'Sora_400Regular',
  },
  restartButton: {
    marginTop: 16,
    backgroundColor: '#0f4c5c',
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: 'center',
  },
  restartButtonText: {
    color: '#ffffff',
    fontFamily: 'Sora_700Bold',
    fontSize: 13,
  },
  footerActions: {
    paddingTop: 8,
    paddingBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  secondaryAction: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: '#dfece9',
  },
  secondaryActionText: {
    color: '#355962',
    fontFamily: 'Sora_600SemiBold',
    fontSize: 13,
  },
  primaryAction: {
    minWidth: 162,
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#0e766e',
  },
  primaryDisabled: {
    opacity: 0.45,
  },
  primaryActionText: {
    color: '#ffffff',
    fontFamily: 'Sora_700Bold',
    fontSize: 13,
  },
});
